#!/usr/bin/env python
# -*- coding: utf-8 -*-
lbl_nmbr_usrs = 'Nombre de usuario'
lbl_cntrsna_usrs = 'Contraseña de usuario'
lbl_nva_cntrsna = 'Nueva Contraseña'
lbl_cdgo_prfl = 'Codigo Perfil'
lbl_dscrpcn_prfl =  'Descripcion Perfil'
lbl_cdgo= 'Codigo'
lbl_prgnta= 'Descripcion Pregunta'
lbl_rspsta='Descripcion Respuesta'
lbl_lgn = 'Login' 
lbl_cntrsna =  'Contraseña'
lbl_id_prfl = 'id Perfil'
lbl_cntrsna = 'Login'
lbl_stts_success = "success"
lbl_stts_error = "error"
SCCSS_RGSTRO_EXTSO='El registro se inserto con Exito'
WRNNG_CDDO='¡Cuidado! Es muy importante que leas este mensaje de alerta.'
INFO_ATNCN='¡Atento! Este mensaje requiere de tu atención, aunque no es tan importante.'
SCCSS_ACTLZCN_EXTSA= 'Actualizacion exitosa'
INFO_NO_DTS ='¡Sin Datos En la Consulta!'
LOGOUT="Bye"
lbl_id_prgnta_ge='id_prgnta_ge'
lbl_id_prgnta='id_prgnta'
lbl_id_mnu='Nodo Superior'
lbl_lnk='Ruta'
lbl_ordn='Orden'
lbl_dscrpcn_mnu = 'Descripcion Menu'
lbl_id_mnu_ge = 'id_mnu_ge'